/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MidiSearchFrame.java
 *
 * Created on 2011/11/24, 20:20:05
 */
package midisearch;

import quicktime.*;
import quicktime.app.time.*;
import quicktime.io.*;
import quicktime.std.*;
import quicktime.std.movies.*;

import java.io.*;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Map;
import java.util.List;
import java.util.Comparator;
import javax.sound.midi.*;

/**
 *
 * @author takanolab
 */
public class MidiSearchFrame extends javax.swing.JFrame {

    Movie movie = null;
    SimpleResultsTableModel tableModel = new SimpleResultsTableModel();
    private EditDistance editDistance = new EditDistance();

    /** Creates new form MidiSearchFrame */
    public MidiSearchFrame() {
        initComponents();
        init();
    }

    public void init() {
        jTableResult.setModel(tableModel);
//        tableModel.addRow(new SimpleResultsTableRow("italco", "italco.mid"));
//        tableModel.addRow(new SimpleResultsTableRow("Nocturne No.2", "noct_2.mid"));
//        tableModel.addRow(new SimpleResultsTableRow("Piano Concerto No.2", "con2_1.mid"));
        new MidiKeyboardW();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResult = new javax.swing.JTable();
        jButtonPlay = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jTextFieldInput = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableResult);

        jButtonPlay.setText("Play");
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jButtonStop.setText("Stop");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jTextFieldInput.setEditable(false);

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldInput)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonPlay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStop)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonClear)
                                .addGap(172, 172, 172)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 54, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonStop)
                    .addComponent(jButtonPlay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
// TODO add your handling code here:
    try {
        QTSessionCheck.check();
        String title = "";
        int row = jTableResult.getSelectedRow();
        if (jTableResult.getSelectedRow() > -1) {

            if (movie != null) {
                movie.stop();
            }

            title = (String) jTableResult.getValueAt(jTableResult.getSelectedRow(), 1);
            String fileName = "midi\\" + title + ".mid";
            System.out.println(fileName);
            QTFile f = new QTFile(new File(fileName));
            OpenMovieFile omf = OpenMovieFile.asRead(f);
            movie = Movie.fromFile(omf);
            TaskAllMovies.addMovieAndStart();
            movie.start();
        } else {
            System.out.println("Not selected");
        }
    } catch (QTException e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_jButtonPlayActionPerformed

private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
// TODO add your handling code here:
    if (movie != null) {
        try {
            movie.stop();
        } catch (QTException e) {
            e.printStackTrace();
        }
    }
}//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String inputnotes = jTextFieldInput.getText();
        String [] notes = inputnotes.split(" ");
        HashMap<String, Integer> results = editDistance.search(notes);
        
        List<Map.Entry> entries = new ArrayList<Map.Entry>(results.entrySet());
        Collections.sort(entries, new Comparator(){
            public int compare(Object o1, Object o2){
                Map.Entry e1 =(Map.Entry)o1;
                Map.Entry e2 =(Map.Entry)o2;
                return ((Integer)e1.getValue()).compareTo((Integer)e2.getValue());
            }
        });
        tableModel.removeAll();
        System.out.println("Search Results:");
        Integer rank = 1;
        for (Map.Entry entry : entries) {
            System.out.println(entry.getKey() + " " + entry.getValue());
            tableModel.addRow(new SimpleResultsTableRow(rank, entry.getKey().toString(), entry.getValue().toString()));
            rank++;
        }
        
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldInput.setText("");
        
        // 検索結果も削除
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MidiSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MidiSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MidiSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MidiSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MidiSearchFrame().setVisible(true);
            }
        });
    }
    
    public class MidiKeyboardW implements Receiver
{
    static final int DEVICE_IN  = 0;
    static final int DEVICE_OUT = 1;//ここを修正、私の場合1or2
    private MidiDevice.Info[] info;
    private MidiDevice in_device = null;
    private MidiDevice out_device = null;
    
    
    
    private final String[]	sm_astrKeyNames = {"C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"};
    private final String[]	sm_astrKeySignatures = {"Cb", "Gb", "Db", "Ab", "Eb", "Bb", "F", "C", "G", "D", "A", "E", "B", "F#", "C#"};


    public MidiKeyboardW() {
        info = MidiSystem.getMidiDeviceInfo();
        MidiDevice dev = null;

        try {
            dev = MidiSystem.getMidiDevice(info[DEVICE_IN]);
        } catch (Throwable t) {
        }

        connectMidiIn(dev);

        try {
            dev = MidiSystem.getMidiDevice(info[DEVICE_OUT]);
        } catch (Throwable t) {
        }
        connectMidiOut(dev);

    }

    private void connectMidiIn(MidiDevice device) {

        try {

            device.open();
            Transmitter tx = device.getTransmitter();
            tx.setReceiver(this);
            in_device = device;

        } catch (MidiUnavailableException e) {
            e.printStackTrace();
        }
    }

    private void connectMidiOut(MidiDevice device) {
        try {
            device.open();
            out_device = device;
        } catch (MidiUnavailableException e) {
            e.printStackTrace();
        }
    }

    public void close() {
    }

    public void send(MidiMessage message, long timeStamp) {

        
        if (message instanceof ShortMessage) {
            ShortMessage sm = (ShortMessage) message;
            String query_notes = "";
            switch (sm.getCommand()) {
                case ShortMessage.NOTE_ON:
                    System.out.println(sm.getData1() + " " + getKeyName(sm.getData1()));
                    query_notes = jTextFieldInput.getText() + " " + getKeyName(sm.getData1());
                    jTextFieldInput.setText(query_notes);
                    break;
                //case ShortMessage.NOTE_OFF:
                //break;
                default:
            }
        }

        try {
            out_device.getReceiver().send(message, timeStamp);
        } catch (MidiUnavailableException e) {
        }

    }
    
    	public String getKeyName(int nKeyNumber)
	{
		if (nKeyNumber > 127)
		{
			return "illegal value";
		}
		else
		{
			int	nNote = nKeyNumber % 12;
			int	nOctave = nKeyNumber / 12;
			return sm_astrKeyNames[nNote] + (nOctave - 1);
		}
	}
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableResult;
    private javax.swing.JTextField jTextFieldInput;
    // End of variables declaration//GEN-END:variables
}
